/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebinarsRouteImport } from './routes/webinars'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as Class12ConsultRouteImport } from './routes/class-12-consult'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopsIndexRouteImport } from './routes/workshops.index'
import { Route as WorkshopsSlugRouteImport } from './routes/workshops.$slug'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WebinarsRoute = WebinarsRouteImport.update({
  id: '/webinars',
  path: '/webinars',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Class12ConsultRoute = Class12ConsultRouteImport.update({
  id: '/class-12-consult',
  path: '/class-12-consult',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsIndexRoute = WorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsSlugRoute = WorkshopsSlugRouteImport.update({
  id: '/workshops/$slug',
  path: '/workshops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/class-12-consult': typeof Class12ConsultRoute
  '/dashboard': typeof DashboardRoute
  '/mentors': typeof MentorsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/webinars': typeof WebinarsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/workshops/': typeof WorkshopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/class-12-consult': typeof Class12ConsultRoute
  '/dashboard': typeof DashboardRoute
  '/mentors': typeof MentorsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/webinars': typeof WebinarsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/workshops': typeof WorkshopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/class-12-consult': typeof Class12ConsultRoute
  '/dashboard': typeof DashboardRoute
  '/mentors': typeof MentorsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/webinars': typeof WebinarsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/workshops/': typeof WorkshopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/class-12-consult'
    | '/dashboard'
    | '/mentors'
    | '/verify-email'
    | '/webinars'
    | '/blog/$slug'
    | '/profile/$userId'
    | '/workshops/$slug'
    | '/workshops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/class-12-consult'
    | '/dashboard'
    | '/mentors'
    | '/verify-email'
    | '/webinars'
    | '/blog/$slug'
    | '/profile/$userId'
    | '/workshops/$slug'
    | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/class-12-consult'
    | '/dashboard'
    | '/mentors'
    | '/verify-email'
    | '/webinars'
    | '/blog/$slug'
    | '/profile/$userId'
    | '/workshops/$slug'
    | '/workshops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  Class12ConsultRoute: typeof Class12ConsultRoute
  DashboardRoute: typeof DashboardRoute
  MentorsRoute: typeof MentorsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WebinarsRoute: typeof WebinarsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  WorkshopsSlugRoute: typeof WorkshopsSlugRoute
  WorkshopsIndexRoute: typeof WorkshopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webinars': {
      id: '/webinars'
      path: '/webinars'
      fullPath: '/webinars'
      preLoaderRoute: typeof WebinarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-12-consult': {
      id: '/class-12-consult'
      path: '/class-12-consult'
      fullPath: '/class-12-consult'
      preLoaderRoute: typeof Class12ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/': {
      id: '/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof WorkshopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/$slug': {
      id: '/workshops/$slug'
      path: '/workshops/$slug'
      fullPath: '/workshops/$slug'
      preLoaderRoute: typeof WorkshopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  Class12ConsultRoute: Class12ConsultRoute,
  DashboardRoute: DashboardRoute,
  MentorsRoute: MentorsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WebinarsRoute: WebinarsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  WorkshopsSlugRoute: WorkshopsSlugRoute,
  WorkshopsIndexRoute: WorkshopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
